version: "2.1"

services:

  api:
    build: ./service/
    volumes:
      - ./service:/src
      - /src/node_modules
    ports:
      - "7000:4000"
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    build: ./db/
    expose:
      - '27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: